const SET_USER = 'SET_USER';
const ALTER_USER = 'ALTER_USER';
const ALTER_JUST_USER = 'ALTER_JUST_USER';
const SET_TOKEN = 'SET_TOKEN';
const SET_BOTTOM_TAB_BAR = 'SET_BOTTOM_TAB_BAR';
const SET_BOTTOM_TAB_BAR_INDEX = 'SET_BOTTOM_TAB_BAR_INDEX';
const SET_LANGUAGE = 'SET_LANGUAGE';
const SET_FEEDS = 'SET_FEEDS';
const SET_STOCK = 'SET_STOCK';
const SET_GAINER = 'SET_GAINER';
const SET_LOOSER = 'SET_LOOSER';

export {
  SET_USER,
  ALTER_USER,
  ALTER_JUST_USER,
  SET_TOKEN,
  SET_BOTTOM_TAB_BAR,
  SET_BOTTOM_TAB_BAR_INDEX,
  SET_LANGUAGE,
  SET_FEEDS,
  SET_STOCK,
  SET_GAINER,
  SET_LOOSER,
};
